import PDFDocument from 'pdfkit';
import { AnalysisResult, Issue } from '../types/index.js';

/**
 * Sanitize text for PDF output
 * Prevents control characters and potential PDF injection
 */
function sanitizeForPdf(text: string | undefined | null): string {
  if (!text) return '';
  
  return text
    // Remove control characters except newlines and tabs
    .replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, '')
    // Normalize whitespace
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n')
    // Remove potential PDF operators
    .replace(/<<|>>/g, '')
    // Limit length to prevent DoS
    .slice(0, 10000);
}

/**
 * Truncate text with ellipsis
 */
function truncate(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text;
  return text.slice(0, maxLength - 3) + '...';
}

class ExportService {
  /**
   * Export analysis to JSON
   */
  exportToJSON(analysis: AnalysisResult & { text: string; id: string }, includeMetadata = true): string {
    const data = {
      id: analysis.id,
      text: analysis.text,
      summary: analysis.summary,
      score: analysis.score,
      issues: analysis.issues,
      analyzedAt: analysis.analyzedAt,
      ...(includeMetadata && { metadata: analysis.metadata }),
      exportedAt: new Date().toISOString(),
      generator: 'Argus Critical Thinking Assistant',
    };

    return JSON.stringify(data, null, 2);
  }

  /**
   * Export analysis to PDF
   */
  async exportToPDF(analysis: AnalysisResult & { text: string; id: string }): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: 'A4',
          margin: 50,
          info: {
            Title: 'Argus Analysis Report',
            Author: 'Argus Critical Thinking Assistant',
            Creator: 'Argus',
          },
        });

        const chunks: Buffer[] = [];
        doc.on('data', (chunk: Buffer) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        // Header
        doc.fontSize(24).fillColor('#6366f1').text('Argus Analysis Report', { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(10).fillColor('#64748b').text(`Generated on ${new Date().toLocaleDateString()}`, { align: 'center' });
        doc.moveDown(2);

        // Score circle
        this.drawScoreSection(doc, analysis.score);
        doc.moveDown(1.5);

        // Summary (sanitized)
        doc.fontSize(14).fillColor('#1e293b').text('Summary');
        doc.moveDown(0.3);
        doc.fontSize(11).fillColor('#475569').text(sanitizeForPdf(analysis.summary));
        doc.moveDown(1.5);

        // Original Text (sanitized and truncated)
        doc.fontSize(14).fillColor('#1e293b').text('Analyzed Text');
        doc.moveDown(0.3);
        const sanitizedText = sanitizeForPdf(analysis.text);
        doc.fontSize(10).fillColor('#64748b').text(
          truncate(sanitizedText, 500),
          { align: 'justify' }
        );
        doc.moveDown(1.5);

        // Issues
        if (analysis.issues.length > 0) {
          doc.fontSize(14).fillColor('#1e293b').text(`Issues Found (${analysis.issues.length})`);
          doc.moveDown(0.5);

          // Limit issues to prevent DoS
          const maxIssues = Math.min(analysis.issues.length, 50);
          for (let i = 0; i < maxIssues; i++) {
            this.drawIssue(doc, analysis.issues[i]);
          }
          
          if (analysis.issues.length > maxIssues) {
            doc.fontSize(10).fillColor('#64748b').text(
              `... and ${analysis.issues.length - maxIssues} more issues`,
              { align: 'center' }
            );
          }
        } else {
          doc.fontSize(12).fillColor('#10b981').text('✓ No critical thinking issues detected!', { align: 'center' });
        }

        // Footer
        doc.moveDown(2);
        doc.fontSize(9).fillColor('#94a3b8').text(
          'Generated by Argus - Your Critical Thinking Assistant',
          { align: 'center' }
        );

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  private drawScoreSection(doc: PDFKit.PDFDocument, score: number) {
    const centerX = doc.page.width / 2;
    const scoreColor = score >= 80 ? '#10b981' : score >= 50 ? '#f59e0b' : '#ef4444';
    const scoreLabel = score >= 80 ? 'Good' : score >= 50 ? 'Fair' : 'Poor';

    // Score value
    doc.fontSize(48).fillColor(scoreColor).text(String(score), centerX - 30, doc.y, { width: 60, align: 'center' });
    doc.fontSize(12).fillColor('#64748b').text(`Logic Score - ${scoreLabel}`, { align: 'center' });
  }

  private drawIssue(doc: PDFKit.PDFDocument, issue: Issue) {
    const severityColors = {
      low: '#10b981',
      medium: '#f59e0b',
      high: '#ef4444',
    };
    const typeIcons = {
      fallacy: '⚠',
      bias: '🧠',
      heuristic: '⚡',
      manipulation: '🎭',
    };

    // Check for page break
    if (doc.y > doc.page.height - 150) {
      doc.addPage();
    }

    // Issue header (sanitized)
    const sanitizedName = sanitizeForPdf(issue.name);
    doc.fontSize(11).fillColor(severityColors[issue.severity] || '#f59e0b');
    doc.text(`${typeIcons[issue.type] || '•'} ${truncate(sanitizedName, 100)}`, { continued: true });
    doc.fillColor('#64748b').text(` (${issue.severity})`, { continued: false });
    doc.moveDown(0.3);

    // Quote (sanitized)
    if (issue.quote) {
      const sanitizedQuote = sanitizeForPdf(issue.quote);
      doc.fontSize(10).fillColor('#6366f1').text(`"${truncate(sanitizedQuote, 200)}"`, { indent: 20 });
      doc.moveDown(0.3);
    }

    // Explanation (sanitized)
    const sanitizedExplanation = sanitizeForPdf(issue.explanation);
    doc.fontSize(10).fillColor('#475569').text(`Why it's problematic: ${truncate(sanitizedExplanation, 300)}`, { indent: 20 });
    doc.moveDown(0.2);

    // Suggestion (sanitized)
    const sanitizedSuggestion = sanitizeForPdf(issue.suggestion);
    doc.fontSize(10).fillColor('#059669').text(`Think critically: ${truncate(sanitizedSuggestion, 300)}`, { indent: 20 });
    doc.moveDown(1);
  }
}

export default new ExportService();
